In [8]:
import numpy as np
import scipy

# Matrix

In [119]:
mtx = np.array(
    [
        [0.5, 1.0, 0.0, 0.0, 0.0],
        [0.0, 0.5, 1.0, 0.0, 0.0],
        [0.0, 0.0, 0.5, 1.0, 0.0],
        [0.0, 0.0, 0.0, 0.5, 1.0],
        [0.0, 0.0, 0.0, 0.0, 0.5]
    ]
)
b = np.array([0.0, 0.0, 0.0, 0.0, 1.0])

In [120]:
mtx

array([[0.5, 1. , 0. , 0. , 0. ],
       [0. , 0.5, 1. , 0. , 0. ],
       [0. , 0. , 0.5, 1. , 0. ],
       [0. , 0. , 0. , 0.5, 1. ],
       [0. , 0. , 0. , 0. , 0.5]])

# Right part

In [121]:
b

array([0., 0., 0., 0., 1.])

In [122]:
class gmres_counter(object):
    def __init__(self, disp=True):
        self._disp = disp
        self.niter = 0
    def __call__(self, rk=None):
        self.niter += 1
        if self._disp:
            print('iter %3i\trk = %s' % (self.niter, str(rk)))

counter = gmres_counter()            

# Solution with iterations

In [123]:
x = scipy.sparse.linalg.gmres(mtx, b, callback=counter)

iter   1	rk = 0.8944271909999159
iter   2	rk = 0.8728715609439694
iter   3	rk = 0.8677218312746245
iter   4	rk = 0.8664485777182116
iter   5	rk = 0.0


In [124]:
scipy.linalg.norm(mtx, ord=2)**2

2.08119816510609

In [125]:
mtx@x[0]

array([0., 0., 0., 0., 1.])

# Find eigen values

In [126]:
scipy.linalg.eig(mtx)

(array([0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j]),
 array([[ 1.00000000e+00, -1.00000000e+00,  1.00000000e+00,
         -1.00000000e+00,  1.00000000e+00],
        [ 0.00000000e+00,  1.11022302e-16, -1.11022302e-16,
          1.11022302e-16, -1.11022302e-16],
        [ 0.00000000e+00,  0.00000000e+00,  1.23259516e-32,
         -1.23259516e-32,  1.23259516e-32],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.36845553e-48, -1.36845553e-48],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  1.51929084e-64]]))

# Check for normal

In [127]:
mtx@mtx.T - mtx.T@mtx

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.]])