In [1]:
import numpy as np

## Task 8.9 

#### Matrix for illustration of 5x5 size

In [2]:
n = 5
example = np.fromfunction(lambda i, j: 1 / (i + j + 1),
                      (n, n),
                      dtype=np.float64
)
print(f'5x5 Matrix: \n\n {example}')

5x5 Matrix: 

 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


#### Matrix from the task of 13x13 size

In [3]:
n = 13
mtx = np.fromfunction(lambda i, j: 1 / (i + j + 1),
                      (n, n),
                      dtype=np.float64
)

### Gram-Schmidt process (Modified)

In [4]:
def gram_schmidt(mtx):
    """
    This function makes rows of 'mtx' orthonormal using Gram - Schmidt Algorithm;
    'mtx' must be numpy.ndarray
    """
    try:
        if not isinstance(mtx, np.ndarray):
            raise NameError('Bad type')
    except NameError:
        raise
        
    for i in range(mtx.shape[0]):
        for j in range(i):
            mtx[i] -= np.dot(mtx[j], mtx[i]) * mtx[j]
        mtx[i] /= np.linalg.norm(mtx[i])
        
    return mtx

#### Results on task matrix:

In [5]:
gram_schmidt(mtx)
qqt = mtx @ mtx.T
error = np.linalg.norm(qqt - np.eye(mtx.shape[0], mtx.shape[1]), ord=2)
print(f'Error in Orthogonalization (||Q*Q - I||) = {error}\n')
for i in range(mtx.shape[0]):
    print(f'Dot product of vectors: 1 and {i + 1} : {np.dot(mtx[0], mtx[i])}')

Error in Orthogonalization (||Q*Q - I||) = 0.8760488897454903

Dot product of vectors: 1 and 1 : 1.0
Dot product of vectors: 1 and 2 : -4.666406150377611e-16
Dot product of vectors: 1 and 3 : 1.2540316007836338e-14
Dot product of vectors: 1 and 4 : -2.0161997071888038e-13
Dot product of vectors: 1 and 5 : 1.1720520387559219e-12
Dot product of vectors: 1 and 6 : 2.4417558253109206e-11
Dot product of vectors: 1 and 7 : -9.514777195296364e-10
Dot product of vectors: 1 and 8 : 1.8927112953315284e-08
Dot product of vectors: 1 and 9 : -2.1594636106375686e-07
Dot product of vectors: 1 and 10 : -2.183694383995835e-06
Dot product of vectors: 1 and 11 : 0.00029928428061603944
Dot product of vectors: 1 and 12 : -0.02101480710248148
Dot product of vectors: 1 and 13 : 0.5763851335640364


### Let`s do Othogonalization again:

In [6]:
gram_schmidt(mtx)
qqt = mtx @ mtx.T
error = np.linalg.norm(qqt - np.eye(mtx.shape[0], mtx.shape[1]), ord=2)
print(f'Error in Orthogonalization (||Q*Q - I||) = {error}\n')
for i in range(mtx.shape[0]):
    print(f'Dot product of vectors: 1 and {i + 1} : {np.dot(mtx[0], mtx[i])}')

Error in Orthogonalization (||Q*Q - I||) = 5.10956120684755e-16

Dot product of vectors: 1 and 1 : 1.0
Dot product of vectors: 1 and 2 : -5.724587470723463e-17
Dot product of vectors: 1 and 3 : 1.734723475976807e-17
Dot product of vectors: 1 and 4 : 2.0816681711721685e-17
Dot product of vectors: 1 and 5 : -5.204170427930421e-17
Dot product of vectors: 1 and 6 : -3.8163916471489756e-17
Dot product of vectors: 1 and 7 : 0.0
Dot product of vectors: 1 and 8 : -2.42861286636753e-17
Dot product of vectors: 1 and 9 : -3.469446951953614e-18
Dot product of vectors: 1 and 10 : -1.0408340855860843e-17
Dot product of vectors: 1 and 11 : 3.122502256758253e-17
Dot product of vectors: 1 and 12 : 2.5153490401663703e-17
Dot product of vectors: 1 and 13 : -9.172350379227368e-17


#### Some Other Examples:

In [7]:
check1 = np.array([[1.0, 2, 3], [1, 3, 2], [1, 1, 2]])
print(check1)

gram_schmidt(check1)
qqt = check1 @ check1.T
error = np.linalg.norm(qqt - np.eye(check1.shape[0], check1.shape[1]), ord=2)
print(f'Error in Orthogonalization (||Q*Q - I||) = {error}')
for i in range(check1.shape[0]):
    print(f'Dot product of vectors: 1 and {i + 1} : {np.dot(check1[0], check1[i])}')

[[1. 2. 3.]
 [1. 3. 2.]
 [1. 1. 2.]]
Error in Orthogonalization (||Q*Q - I||) = 5.900914567056208e-16
Dot product of vectors: 1 and 1 : 1.0
Dot product of vectors: 1 and 2 : -2.220446049250313e-16
Dot product of vectors: 1 and 3 : -3.608224830031759e-16


#### Random Matrix 1000x1000

In [8]:
check2 = np.random.rand(1000, 1000)

gram_schmidt(check2)
qqt = check2 @ check2.T
error = np.linalg.norm(qqt - np.eye(check2.shape[0], check2.shape[1]), ord=2)
print(f'Error in Orthogonalization (||Q*Q - I||) = {error}')

Error in Orthogonalization (||Q*Q - I||) = 3.398053768003163e-13
